import { NextRequest, NextResponse } from 'next/server';

interface FileSpec { path: string; content: string }

function generateSite(owner: string, repo: string): FileSpec[] {
  return [
    {
      path: 'README.md',
      content: `# ${repo}\n\nA landing page generated by QuarterBack.\n\n## Deploy\n\`\`\`bash\nnpm install\nnpm run build\nnpm run preview\n\`\`\`\n\nGenerated by [QuarterBack](https://agentdatasync.com) — the operating system for agencies.\n`,
    },
    {
      path: 'index.html',
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${repo} — Built with QuarterBack</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{font-family:system-ui,-apple-system,sans-serif;background:#0B1426;color:#fff;min-height:100vh}
    .hero{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:2rem}
    .badge{font-size:0.7rem;letter-spacing:0.2em;text-transform:uppercase;color:#c9a227;margin-bottom:1.5rem}
    h1{font-size:clamp(2.5rem,6vw,5rem);font-weight:300;line-height:1.1;margin-bottom:1rem}
    h1 em{font-style:normal;color:#c9a227}
    .sub{color:#94a3b8;font-size:1.1rem;max-width:600px;margin:0 auto 2rem;line-height:1.6}
    .cta{display:inline-block;padding:14px 32px;background:#c9a227;color:#0B1426;border-radius:12px;font-weight:600;font-size:1rem;text-decoration:none;transition:all .15s}
    .cta:hover{opacity:0.9;transform:scale(1.02)}
    .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1.5rem;margin-top:4rem;max-width:400px;width:100%}
    .stat{text-align:center}
    .stat .val{font-size:1.8rem;font-weight:600;color:#c9a227}
    .stat .lbl{font-size:0.7rem;color:#64748b;text-transform:uppercase;letter-spacing:0.15em;margin-top:0.25rem}
    @keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}
    .hero>*{animation:fadeUp .7s cubic-bezier(.16,1,.3,1) both}
    .hero>:nth-child(2){animation-delay:.1s}
    .hero>:nth-child(3){animation-delay:.2s}
    .hero>:nth-child(4){animation-delay:.3s}
  </style>
</head>
<body>
  <section class="hero">
    <p class="badge">Built with QuarterBack</p>
    <h1>${repo.replace(/-/g, ' ')}<br/><em>your agency, automated.</em></h1>
    <p class="sub">This page was generated and deployed by a single command from QuarterBack — the operating system that runs your agency without you.</p>
    <a href="https://agentdatasync.com/command" class="cta">Try QuarterBack Free →</a>
    <div class="stats">
      <div class="stat"><div class="val">22</div><div class="lbl">Agents</div></div>
      <div class="stat"><div class="val">315</div><div class="lbl">Points</div></div>
      <div class="stat"><div class="val">0</div><div class="lbl">Shelf-ware</div></div>
    </div>
  </section>
</body>
</html>
`,
    },
  ];
}
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const command = body.command?.trim();
    const token = process.env.GITHUB_TOKEN;
    if (!token) return NextResponse.json({ ok: false, error: 'GITHUB_TOKEN not set' }, { status: 500 });

    // Parse repo name from command
    const slugMatch = command?.match(/(?:ship|deploy|push|create|launch)\s+(?:a\s+)?(?:repo|site|page|website)?\s*(?:for|called|named|as)?\s*([a-zA-Z0-9_-]+)/i);
    const repoName = slugMatch ? slugMatch[1].replace(/\s+/g, '-').toLowerCase().slice(0, 50) : `q-${Date.now().toString(36)}`;
    const owner = 'ypc-ux';
    const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json' };

    // Create repo
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,
      body: JSON.stringify({ name: repoName, description: `Generated by QuarterBack — ${command}`, private: false, auto_init: false }),
    });
    if (!createRes.ok) {
      const err = await createRes.text().catch(() => '');
      if (createRes.status === 422 && err.includes('already_exists')) {
        return NextResponse.json({ ok: false, error: `Repo ${owner}/${repoName} already exists. Try a different name.` }, { status: 409 });
      }
      return NextResponse.json({ ok: false, error: `GitHub API error ${createRes.status}: ${err.slice(0, 200)}` }, { status: 500 });
    }
    const repoData = await createRes.json();

    // Generate files and push via Tree API
    const files = generateSite(owner, repoName);
    const tree = files.map(f => ({
      path: f.path,
      mode: '100644',
      type: 'blob',
      content: f.content,
    }));

    // Create tree
    const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/trees`, {
      method: 'POST', headers,
      body: JSON.stringify({ tree }),
    });
    const treeData = await treeRes.json();

    // Create commit
    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits`, {
      method: 'POST', headers,
      body: JSON.stringify({ message: `feat: initial site — ${command}\n\nGenerated by QuarterBack (agentdatasync.com)`, tree: treeData.sha }),
    });
    const commitData = await commitRes.json();

    // Update ref
    await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs`, {
      method: 'POST', headers,
      body: JSON.stringify({ ref: 'refs/heads/main', sha: commitData.sha }),
    });

    // Enable GitHub Pages
    await fetch(`https://api.github.com/repos/${owner}/${repoName}/pages`, {
      method: 'POST', headers,
      body: JSON.stringify({ source: { branch: 'main', path: '/' } }),
    }).catch(() => {});

    const repoUrl = `https://github.com/${owner}/${repoName}`;
    const pagesUrl = `https://${owner}.github.io/${repoName}`;

    return NextResponse.json({
      ok: true,
      repo: repoName,
      owner,
      repo_url: repoUrl,
      pages_url: pagesUrl,
      files_created: files.length,
      command,
    });
  } catch (err: any) {
    return NextResponse.json({ ok: false, error: err.message || 'Unknown error' }, { status: 500 });
  }
}